package br.com.caiosousa.maven.plugin;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;

/**
 * @goal basicplugin
 * 
 * @phase process-sources
 */
public class BasicMojo extends AbstractMojo {
   
	/**
     * Location of the test file.
     * 
     * @parameter expression="${project.build.directory}/${project.build.finalName}/testplugin"
     * @required
     */
    private File testDirectory;
    
    public void execute() throws MojoExecutionException {
        
        if (!this.testDirectory.exists()) {
        	this.testDirectory.mkdirs();
        }

        final File file = new File(testDirectory, "test.txt" );
        
        try (FileWriter fileWriter = new FileWriter(file);) {
	        
	        fileWriter.write( "This is a simple file generated by basic maven plugin.");
			
		} catch (IOException e) {
			e.printStackTrace();
		}
        
    }
}
